NOTE: The production of an assertion error might be part of the test.
---------------------------------------------------------------------
received: ONE
received: TWO
received: THREE
received: FOUR
received: FIVE
received: ONE
received: TWO
received: THREE
received: FOUR
received: FIVE
received: ONE
received: TWO
received: THREE
received: FOUR
received: FIVE
received: ONE
received: TWO
received: THREE
received: FOUR
received: FIVE
terminate called after throwing an instance of 'std::runtime_error'
  what():  
    Match failure in mode 'REAL'.
    No 'on_failure' section provided for this mode.
    Proposal: Define 'on_failure' and analyze 'Lexeme'.
